global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ejournal-backend'
    static_configs:
      - targets: ['ejournal-backend:8888']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
