package app

import (
	"context"
	"fmt"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/TelecomDep/ejournal_backend/internal/db"
	"github.com/jackc/pgx/v5/pgxpool"
)

func TestRegistrationAgreementCommitsAndRollsBackWithAccount(t *testing.T) {
	dsn := os.Getenv("TEST_DB_DSN")
	if dsn == "" {
		t.Skip("TEST_DB_DSN is not set")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		t.Fatal(err)
	}
	defer pool.Close()
	var name string
	if err := pool.QueryRow(ctx, "SELECT current_database()").Scan(&name); err != nil {
		t.Fatal(err)
	}
	if strings.EqualFold(name, "ejournal") {
		t.Fatal("use a dedicated test database, not ejournal")
	}
	if _, err := pool.Exec(ctx, "CREATE EXTENSION IF NOT EXISTS pgcrypto"); err != nil {
		t.Fatal(err)
	}
	schema := fmt.Sprintf("registration_consent_test_%d", time.Now().UnixNano())
	if _, err := pool.Exec(ctx, "CREATE SCHEMA "+schema); err != nil {
		t.Fatal(err)
	}
	defer func() {
		cleanupCtx, cleanupCancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cleanupCancel()
		if _, err := pool.Exec(cleanupCtx, "DROP SCHEMA "+schema+" CASCADE"); err != nil {
			t.Error(err)
		}
	}()
	if _, err := pool.Exec(ctx, attendanceAuthorizationSchemaSQL(schema)); err != nil {
		t.Fatal(err)
	}
	storeDSN, err := attendanceAuthorizationDSN(dsn, schema)
	if err != nil {
		t.Fatal(err)
	}
	store, err := db.NewStore(ctx, storeDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	_, err = store.Pool().Exec(ctx, `
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
CREATE TABLE registration_invites (
    invite_id SERIAL PRIMARY KEY,
    role TEXT NOT NULL,
    student_id INTEGER,
    teacher_id INTEGER,
    invite_code_hash TEXT NOT NULL,
    used_at TIMESTAMPTZ
);
CREATE TABLE user_agreement_decisions (
    decision_id BIGSERIAL PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    agreement_key TEXT NOT NULL,
    version TEXT NOT NULL,
    decision TEXT NOT NULL,
    document_hash TEXT NOT NULL,
    actor_login TEXT NOT NULL CHECK (actor_login <> 'must_rollback'),
    actor_role TEXT NOT NULL,
    ip INET,
    user_agent TEXT,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
INSERT INTO students (student_id,student_name) VALUES (1001,'First'),(1002,'Second');
INSERT INTO registration_invites (role,student_id,invite_code_hash)
VALUES ('student',1001,crypt('FIRST-INVITE',gen_salt('bf',4))),
       ('student',1002,crypt('SECOND-INVITE',gen_salt('bf',4)));
`)
	if err != nil {
		t.Fatal(err)
	}
	svc := NewService("integration-test-jwt-key-1234567890", "https://test.invalid", "", "", 0, false, store, nil)
	agreement := &UserAgreementDecisionData{Version: currentAgreementVersion, Decision: "accepted"}
	meta := RequestMeta{IP: "192.0.2.4", UserAgent: "ConsentIntegrationTest"}

	result := svc.registerByInvite(RegisterByInviteData{Login: "consent_success", Password: "TestPassword123!", InviteCode: "FIRST-INVITE", Agreement: agreement}, meta)
	if !result.OK {
		t.Fatalf("registration failed: %s", result.Error)
	}
	var persisted bool
	err = store.Pool().QueryRow(ctx, `SELECT EXISTS (
SELECT 1 FROM users u
JOIN students s ON s.user_id=u.id
JOIN registration_invites i ON i.student_id=s.student_id
JOIN user_agreement_decisions d ON d.user_id=u.id
WHERE u.login='consent_success' AND i.used_at IS NOT NULL
AND d.version=$1 AND d.decision='accepted' AND d.ip='192.0.2.4'
AND d.user_agent='ConsentIntegrationTest' AND d.document_hash=$2
)`, currentAgreementVersion, currentAgreementDocumentHash()).Scan(&persisted)
	if err != nil || !persisted {
		t.Fatalf("account, profile, invite and consent not persisted together: %v", err)
	}

	result = svc.registerByInvite(RegisterByInviteData{Login: "must_rollback", Password: "TestPassword123!", InviteCode: "SECOND-INVITE", Agreement: agreement}, meta)
	if result.OK || result.Error != "failed to save agreement decision" {
		t.Fatalf("expected consent storage error, got %#v", result)
	}
	var rolledBack bool
	err = store.Pool().QueryRow(ctx, `SELECT
NOT EXISTS (SELECT 1 FROM users WHERE login='must_rollback')
AND EXISTS (SELECT 1 FROM students WHERE student_id=1002 AND user_id IS NULL)
AND EXISTS (SELECT 1 FROM registration_invites WHERE student_id=1002 AND used_at IS NULL)
AND NOT EXISTS (SELECT 1 FROM user_agreement_decisions WHERE actor_login='must_rollback')`).Scan(&rolledBack)
	if err != nil || !rolledBack {
		t.Fatalf("registration did not roll back on consent failure: %v", err)
	}

	result = svc.registerByInvite(RegisterByInviteData{Login: "consent_retry", Password: "TestPassword123!", InviteCode: "SECOND-INVITE", Agreement: agreement}, meta)
	if !result.OK {
		t.Fatalf("invite could not be retried after rollback: %s", result.Error)
	}
}
