-- +goose Up
-- +goose StatementBegin
CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE students DROP CONSTRAINT IF EXISTS students_student_id_role_fkey;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'students'
          AND column_name = 'student_id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE students ALTER COLUMN student_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS invite_code VARCHAR(100);

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS invite_code_hash TEXT;

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS invite_code_used_at TIMESTAMPTZ;

CREATE UNIQUE INDEX IF NOT EXISTS idx_students_user_id_unique
    ON students (user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_students_invite_code_unique
    ON students (invite_code)
    WHERE invite_code IS NOT NULL;

UPDATE students
SET invite_code = UPPER(TRIM(invite_code))
WHERE invite_code IS NOT NULL
  AND invite_code <> UPPER(TRIM(invite_code));

UPDATE students
SET invite_code_hash = crypt(UPPER(invite_code), gen_salt('bf', 10))
WHERE invite_code IS NOT NULL
  AND invite_code_hash IS NULL;

CREATE OR REPLACE FUNCTION students_prepare_invite_code() RETURNS trigger AS $$
BEGIN
    IF NEW.invite_code IS NULL OR BTRIM(NEW.invite_code) = '' THEN
        NEW.invite_code := NULL;
        NEW.invite_code_hash := NULL;
        RETURN NEW;
    END IF;

    IF TG_OP = 'INSERT' OR NEW.invite_code IS DISTINCT FROM OLD.invite_code THEN
        NEW.invite_code := UPPER(BTRIM(NEW.invite_code));
        NEW.invite_code_hash := crypt(NEW.invite_code, gen_salt('bf', 10));
        NEW.invite_code_used_at := NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_students_prepare_invite_code ON students;
CREATE TRIGGER trg_students_prepare_invite_code
BEFORE INSERT OR UPDATE ON students
FOR EACH ROW
EXECUTE FUNCTION students_prepare_invite_code();

SELECT setval(
    pg_get_serial_sequence('students', 'student_id'),
    COALESCE((SELECT MAX(student_id) FROM students), 1),
    true
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trg_students_prepare_invite_code ON students;
DROP FUNCTION IF EXISTS students_prepare_invite_code();

DROP INDEX IF EXISTS idx_students_invite_code_unique;
DROP INDEX IF EXISTS idx_students_user_id_unique;

ALTER TABLE students DROP COLUMN IF EXISTS invite_code_used_at;
ALTER TABLE students DROP COLUMN IF EXISTS invite_code_hash;
ALTER TABLE students DROP COLUMN IF EXISTS invite_code;
-- +goose StatementEnd
