-- +goose Up
-- +goose StatementBegin
ALTER TABLE teachers DROP CONSTRAINT IF EXISTS teachers_teacher_id_role_fkey;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'teachers'
          AND column_name = 'teacher_id'
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE teachers ALTER COLUMN teacher_id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS idx_teachers_user_id_unique
    ON teachers (user_id)
    WHERE user_id IS NOT NULL;

ALTER TABLE schedules
    ADD COLUMN IF NOT EXISTS week_type SMALLINT NOT NULL DEFAULT 1;

ALTER TABLE schedules
    ADD COLUMN IF NOT EXISTS day_idx_raw INTEGER;

ALTER TABLE schedules DROP CONSTRAINT IF EXISTS schedules_day_idx_check;
ALTER TABLE schedules
    ADD CONSTRAINT schedules_day_idx_check CHECK (day_idx BETWEEN 1 AND 7);

ALTER TABLE schedules DROP CONSTRAINT IF EXISTS schedules_week_type_check;
ALTER TABLE schedules
    ADD CONSTRAINT schedules_week_type_check CHECK (week_type IN (1, 2));

CREATE OR REPLACE FUNCTION normalize_schedule_day_idx() RETURNS trigger AS $$
BEGIN
    IF NEW.day_idx BETWEEN 0 AND 13 THEN
        NEW.day_idx_raw := NEW.day_idx;
        NEW.week_type := CASE WHEN NEW.day_idx < 7 THEN 1 ELSE 2 END;
        NEW.day_idx := (NEW.day_idx % 7) + 1;
    ELSE
        NEW.day_idx_raw := COALESCE(NEW.day_idx_raw, NEW.day_idx);
        NEW.week_type := COALESCE(NEW.week_type, 1);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_normalize_schedule_day_idx ON schedules;
CREATE TRIGGER trg_normalize_schedule_day_idx
BEFORE INSERT OR UPDATE ON schedules
FOR EACH ROW
EXECUTE FUNCTION normalize_schedule_day_idx();

UPDATE schedules
SET day_idx_raw = day_idx,
    week_type = COALESCE(week_type, 1)
WHERE day_idx_raw IS NULL;

CREATE OR REPLACE FUNCTION sync_groups_sequence_after_insert() RETURNS trigger AS $$
BEGIN
    PERFORM setval(
        pg_get_serial_sequence('groups', 'group_id'),
        GREATEST(
            COALESCE((SELECT MAX(group_id) FROM groups), 1),
            NEW.group_id
        ),
        true
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_groups_sequence_after_insert ON groups;
CREATE TRIGGER trg_sync_groups_sequence_after_insert
AFTER INSERT ON groups
FOR EACH ROW
EXECUTE FUNCTION sync_groups_sequence_after_insert();

CREATE OR REPLACE FUNCTION sync_teachers_sequence_after_insert() RETURNS trigger AS $$
BEGIN
    PERFORM setval(
        pg_get_serial_sequence('teachers', 'teacher_id'),
        GREATEST(
            COALESCE((SELECT MAX(teacher_id) FROM teachers), 1),
            NEW.teacher_id
        ),
        true
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_teachers_sequence_after_insert ON teachers;
CREATE TRIGGER trg_sync_teachers_sequence_after_insert
AFTER INSERT ON teachers
FOR EACH ROW
EXECUTE FUNCTION sync_teachers_sequence_after_insert();

SELECT setval(
    pg_get_serial_sequence('groups', 'group_id'),
    COALESCE((SELECT MAX(group_id) FROM groups), 1),
    true
);

SELECT setval(
    pg_get_serial_sequence('teachers', 'teacher_id'),
    COALESCE((SELECT MAX(teacher_id) FROM teachers), 1),
    true
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TRIGGER IF EXISTS trg_sync_teachers_sequence_after_insert ON teachers;
DROP FUNCTION IF EXISTS sync_teachers_sequence_after_insert();

DROP TRIGGER IF EXISTS trg_sync_groups_sequence_after_insert ON groups;
DROP FUNCTION IF EXISTS sync_groups_sequence_after_insert();

DROP TRIGGER IF EXISTS trg_normalize_schedule_day_idx ON schedules;
DROP FUNCTION IF EXISTS normalize_schedule_day_idx();

ALTER TABLE schedules DROP CONSTRAINT IF EXISTS schedules_week_type_check;
ALTER TABLE schedules DROP CONSTRAINT IF EXISTS schedules_day_idx_check;

ALTER TABLE schedules
    ADD CONSTRAINT schedules_day_idx_check CHECK (day_idx BETWEEN 1 AND 7);

ALTER TABLE schedules DROP COLUMN IF EXISTS day_idx_raw;
ALTER TABLE schedules DROP COLUMN IF EXISTS week_type;

DROP INDEX IF EXISTS idx_teachers_user_id_unique;
-- +goose StatementEnd
