-- +goose Up
-- +goose StatementBegin
ALTER TABLE grade_items
    ADD COLUMN IF NOT EXISTS created_by_teacher_id INTEGER REFERENCES teachers(teacher_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS delete_reason TEXT;

ALTER TABLE grades
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS deleted_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS delete_reason TEXT;

-- Existing items predate ownership. Recover it from the first grade when possible;
-- items without grades deliberately remain ownerless and can only be removed by admin.
UPDATE grade_items gi
SET created_by_teacher_id = (
    SELECT gr.teacher_id
    FROM grades gr
    WHERE gr.item_id = gi.item_id
      AND gr.teacher_id IS NOT NULL
    ORDER BY gr.created_at, gr.grade_id
    LIMIT 1
)
WHERE gi.created_by_teacher_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM grades gr
      WHERE gr.item_id = gi.item_id
        AND gr.teacher_id IS NOT NULL
  );

CREATE TABLE IF NOT EXISTS grade_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_id INTEGER REFERENCES grades(grade_id) ON DELETE SET NULL,
    grade_item_id INTEGER NOT NULL REFERENCES grade_items(item_id) ON DELETE RESTRICT,
    student_id INTEGER REFERENCES students(student_id) ON DELETE SET NULL,
    actor_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    event_type VARCHAR(40) NOT NULL CHECK (event_type IN (
        'grade_item_created', 'grade_item_deleted', 'grade_item_restored',
        'grade_created', 'grade_updated', 'grade_deleted', 'grade_restored'
    )),
    old_score INTEGER,
    new_score INTEGER,
    reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_grade_items_active_subject
    ON grade_items (subject_id, deadline, item_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_grades_active_item_student
    ON grades (item_id, student_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_grades_active_student_item
    ON grades (student_id, item_id)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_grade_events_item_created
    ON grade_events (grade_item_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.check_subject_score_limit()
RETURNS TRIGGER AS $$
DECLARE
    total_max INTEGER;
BEGIN
    SELECT COALESCE(SUM(max_score), 0)
    INTO total_max
    FROM public.grade_items
    WHERE subject_id = NEW.subject_id
      AND deleted_at IS NULL
      AND item_id IS DISTINCT FROM NEW.item_id;

    IF NEW.deleted_at IS NULL AND (total_max + NEW.max_score) > 100 THEN
        RAISE EXCEPTION 'Суммарный балл по предмету (БРС) не может превышать 100. Текущая сумма: %', total_max;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS idx_grade_events_item_created;
DROP INDEX IF EXISTS idx_grades_active_student_item;
DROP INDEX IF EXISTS idx_grades_active_item_student;
DROP INDEX IF EXISTS idx_grade_items_active_subject;
DROP TABLE IF EXISTS grade_events;

ALTER TABLE grades
    DROP COLUMN IF EXISTS delete_reason,
    DROP COLUMN IF EXISTS deleted_by_user_id,
    DROP COLUMN IF EXISTS deleted_at;

ALTER TABLE grade_items
    DROP COLUMN IF EXISTS delete_reason,
    DROP COLUMN IF EXISTS deleted_by_user_id,
    DROP COLUMN IF EXISTS deleted_at,
    DROP COLUMN IF EXISTS created_by_teacher_id;

CREATE OR REPLACE FUNCTION public.check_subject_score_limit()
RETURNS TRIGGER AS $$
DECLARE
    total_max INTEGER;
BEGIN
    SELECT COALESCE(SUM(max_score), 0)
    INTO total_max
    FROM public.grade_items
    WHERE subject_id = NEW.subject_id
      AND item_id IS DISTINCT FROM NEW.item_id;

    IF (total_max + NEW.max_score) > 100 THEN
        RAISE EXCEPTION 'Суммарный балл по предмету (БРС) не может превышать 100. Текущая сумма: %', total_max;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- +goose StatementEnd
