-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.grade_items (
    item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id INTEGER NOT NULL REFERENCES public.subjects(subject_id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    max_score INTEGER NOT NULL DEFAULT 0 CONSTRAINT grade_items_positive_max_score CHECK (max_score > 0),
    item_type VARCHAR(50) NOT NULL DEFAULT 'current',
    deadline TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.grades (
    grade_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES public.students(student_id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES public.grade_items(item_id) ON DELETE CASCADE,
    teacher_id INTEGER REFERENCES public.teachers(teacher_id) ON DELETE SET NULL,
    score INTEGER NOT NULL DEFAULT 0 CONSTRAINT grades_non_negative_score CHECK (score >= 0),
    session_id INTEGER REFERENCES public.attendance_sessions(session_id) ON DELETE SET NULL,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (student_id, item_id)
);

CREATE OR REPLACE FUNCTION public.check_subject_score_limit()
RETURNS TRIGGER AS $$
DECLARE
    total_max INTEGER;
BEGIN
    SELECT COALESCE(SUM(max_score), 0)
    INTO total_max
    FROM public.grade_items
    WHERE subject_id = NEW.subject_id
      AND item_id IS DISTINCT FROM NEW.item_id;

    IF (total_max + NEW.max_score) > 100 THEN
        RAISE EXCEPTION 'Суммарный балл по предмету (БРС) не может превышать 100. Текущая сумма: %', total_max;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_limit_subject_scores ON public.grade_items;
CREATE TRIGGER trg_limit_subject_scores
    BEFORE INSERT OR UPDATE ON public.grade_items
    FOR EACH ROW
    EXECUTE FUNCTION public.check_subject_score_limit();

CREATE OR REPLACE FUNCTION public.check_grade_score_limit()
RETURNS TRIGGER AS $$
DECLARE
    item_max INTEGER;
BEGIN
    SELECT max_score
    INTO item_max
    FROM public.grade_items
    WHERE item_id = NEW.item_id;

    IF item_max IS NULL THEN
        RAISE EXCEPTION 'Контрольная точка оценки не найдена';
    END IF;

    IF NEW.score > item_max THEN
        RAISE EXCEPTION 'Оценка не может превышать максимум за контрольную точку (%)', item_max;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_limit_grade_score ON public.grades;
CREATE TRIGGER trg_limit_grade_score
    BEFORE INSERT OR UPDATE ON public.grades
    FOR EACH ROW
    EXECUTE FUNCTION public.check_grade_score_limit();

CREATE OR REPLACE FUNCTION public.update_grades_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_grades_timestamp ON public.grades;
CREATE TRIGGER trg_update_grades_timestamp
    BEFORE UPDATE ON public.grades
    FOR EACH ROW
    EXECUTE FUNCTION public.update_grades_updated_at();

CREATE INDEX IF NOT EXISTS idx_grade_items_subject ON public.grade_items (subject_id);
CREATE INDEX IF NOT EXISTS idx_grade_items_deadline ON public.grade_items (deadline);
CREATE INDEX IF NOT EXISTS idx_grades_student_lookup ON public.grades (student_id, item_id);
CREATE INDEX IF NOT EXISTS idx_grades_item_lookup ON public.grades (item_id, student_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP INDEX IF EXISTS public.idx_grades_item_lookup;
DROP INDEX IF EXISTS public.idx_grades_student_lookup;
DROP INDEX IF EXISTS public.idx_grade_items_deadline;
DROP INDEX IF EXISTS public.idx_grade_items_subject;

DROP TRIGGER IF EXISTS trg_update_grades_timestamp ON public.grades;
DROP TRIGGER IF EXISTS trg_limit_grade_score ON public.grades;
DROP TRIGGER IF EXISTS trg_limit_subject_scores ON public.grade_items;

DROP FUNCTION IF EXISTS public.update_grades_updated_at();
DROP FUNCTION IF EXISTS public.check_grade_score_limit();
DROP FUNCTION IF EXISTS public.check_subject_score_limit();

DROP TABLE IF EXISTS public.grades;
DROP TABLE IF EXISTS public.grade_items;
-- +goose StatementEnd
