/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/auth/forgot-password": {
    /** Generates a password reset token and sends it to the user's email. */
    post: {
      parameters: {
        body: {
          /** Forgot password payload */
          request: definitions["app.ForgotPasswordData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/auth/reset-password": {
    /** Resets user password using the provided reset token. */
    post: {
      parameters: {
        body: {
          /** Reset password payload */
          request: definitions["app.ResetPasswordData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/staff/overview": {
    /** Returns groups, teachers and students scoped to the caller's role: teacher -> own groups, head -> own lectern, dean -> own faculty, admin -> everything. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/staff/reports/performance.pdf": {
    /** Head, dean, or admin downloads a PDF performance rating report: one page (or more) for the whole scope plus one section per group, colour-coded by percent, matching the xlsx report. */
    get: {
      responses: {
        /** PDF document */
        200: {
          schema: unknown;
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/staff/reports/performance.xlsx": {
    /** Head, dean, or admin downloads an xlsx performance rating report: one sheet for the whole scope plus one sheet per group. Rows are students ranked by overall rating with per-subject percents and attendance. */
    get: {
      responses: {
        /** Excel workbook */
        200: {
          schema: unknown;
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/attendance/confirm": {
    /** Student confirms attendance for active session. */
    post: {
      parameters: {
        body: {
          /** Attendance confirm payload */
          request: definitions["app.AttendanceConfirmData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.studentAttendanceConfirmResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Conflict */
        409: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/attendance/history": {
    /** Returns attendance marks grouped by date for current student and selected year. */
    get: {
      parameters: {
        query: {
          /** History year */
          year?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.studentAttendanceHistoryResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/grades": {
    /** Student gets own grade sheet for a subject. */
    post: {
      parameters: {
        body: {
          /** Subject payload */
          request: definitions["app.GradeSubjectData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/grades/all": {
    /** Returns every plan subject with its grade items and per-subject totals, plus an aggregate summary, in one request. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/mark-attendance": {
    /** Student marks attendance with lesson ID, device ID, and current location. */
    post: {
      parameters: {
        body: {
          /** Android attendance payload */
          request: definitions["app.AndroidAttendanceMarkData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Conflict */
        409: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/performance/radar": {
    /** Returns one point per subject (from the student's group schedule) with the score/percent the student earned on graded-so-far work this semester. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/student/schedule/day": {
    /** Returns the current student's lessons for a given date, restricted to the current or next calendar week. Defaults to today if date is omitted. */
    get: {
      parameters: {
        query: {
          /** Date in YYYY-MM-DD format (defaults to today) */
          date?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance-link": {
    /** Teacher creates attendance session and gets invite/join URL. If subject_id/group_ids are omitted, they are taken from nearest scheduled lesson. */
    post: {
      parameters: {
        body: {
          /** Attendance session payload (subject_id/group_ids are optional) */
          request: definitions["httpserver.teacherAttendanceLinkRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceLinkResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/group": {
    /** Returns per-student attendance stats for selected group and optional subject. */
    post: {
      parameters: {
        body: {
          /** Group stats payload */
          request: definitions["app.AttendanceGroupStatsData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceGroupResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/mark": {
    /** Teacher sets a student's attendance status (present/absent/late/excused) for a session they own, overriding self/device check-in. */
    post: {
      parameters: {
        body: {
          /** Lesson, student and new status */
          request: definitions["app.TeacherAttendanceMarkData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/session": {
    /** Teacher creates attendance session and gets invite/join URL. If subject_id/group_ids are omitted, they are taken from nearest scheduled lesson. */
    post: {
      parameters: {
        body: {
          /** Attendance session payload (subject_id/group_ids are optional) */
          request: definitions["httpserver.teacherAttendanceLinkRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceLinkResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/session/active": {
    /** Returns current teacher attendance session that has not expired yet. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherActiveAttendanceSessionResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/session/marked-count": {
    /** Returns how many students have marked attendance in a teacher-owned session. */
    get: {
      parameters: {
        query: {
          /** Attendance session ID */
          lesson_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceMarkedCountResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/session/timer": {
    /** Returns remaining seconds for a teacher-owned attendance session. */
    get: {
      parameters: {
        query: {
          /** Attendance session ID */
          lesson_id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceSessionTimerResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/attendance/student/history": {
    /** Teacher gets the detailed attendance history of a specific student for a specific subject. */
    post: {
      parameters: {
        body: {
          /** Student and subject payload */
          request: definitions["app.TeacherAttendanceStudentHistoryData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherAttendanceStudentHistoryResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/grades": {
    /** Teacher creates or updates a student's score for a grade item. */
    post: {
      parameters: {
        body: {
          /** Grade payload */
          request: definitions["app.GradeUpsertData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/grades/items": {
    /** Teacher creates a subject grade item/control point. */
    post: {
      parameters: {
        body: {
          /** Grade item payload */
          request: definitions["app.GradeItemCreateData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/grades/items/list": {
    /** Teacher lists grade items/control points for assigned subject. */
    post: {
      parameters: {
        body: {
          /** Subject payload */
          request: definitions["app.GradeSubjectData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/grades/student": {
    /** Teacher gets a student's grade sheet for an assigned subject. */
    post: {
      parameters: {
        body: {
          /** Student subject payload */
          request: definitions["app.TeacherStudentGradesData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/group/performance": {
    /** Teacher gets a combined per-student overview (attendance and grade totals) for a group on a subject. */
    post: {
      parameters: {
        body: {
          /** Group and subject payload */
          request: definitions["app.GroupPerformanceData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.teacherGroupPerformanceResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/student/performance/radar": {
    /** Teacher gets the per-subject performance radar for a student they teach. */
    post: {
      parameters: {
        body: {
          /** Student payload */
          request: definitions["app.TeacherStudentRadarData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Not Found */
        404: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/teacher/subjects": {
    /** Returns subjects (and groups) assigned to current teacher from schedule. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/user/email": {
    /** Links/updates email for current user. */
    post: {
      parameters: {
        body: {
          /** Update email payload */
          request: definitions["app.UpdateEmailData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/api/user/upload-avatar": {
    /** Saves a JPEG, PNG, or WebP profile picture up to 5 MiB and returns its public URL. */
    post: {
      parameters: {
        formData: {
          /** Avatar image */
          avatar: unknown;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/lessons/create": {
    /** Teacher creates an attendance lesson using subject/group names or IDs and current location. */
    post: {
      parameters: {
        body: {
          /** Android lesson payload */
          request: definitions["app.AndroidLessonCreateData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["app.Response"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Forbidden */
        403: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/login": {
    /** Authenticates a user and returns JWT token. */
    post: {
      parameters: {
        body: {
          /** Login payload */
          request: definitions["app.LoginData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.loginResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/profile": {
    /** Returns current user profile from Authorization token. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.profileResponse"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/register": {
    /** Registers a user by one-time invite_code. Legacy role_hash registration remains supported for existing clients. */
    post: {
      parameters: {
        body: {
          /** Register payload */
          request: definitions["app.RegisterData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.registerResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
  "/register/by-invite": {
    /** Creates student, teacher, or admin account by one-time invite code from database. */
    post: {
      parameters: {
        body: {
          /** Register by invite payload */
          request: definitions["app.RegisterByInviteData"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpserver.registerByInviteResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["app.Response"];
        };
        /** Conflict */
        409: {
          schema: definitions["app.Response"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["app.Response"];
        };
      };
    };
  };
}

export interface definitions {
  "app.AndroidAttendanceMarkData": {
    device_id?: string;
    invite_token?: string;
    lat?: number;
    lesson_id?: number;
    lon?: number;
  };
  "app.AndroidLessonCreateData": {
    expires_minutes?: number;
    group_ids?: number[];
    groups?: string[];
    lat?: number;
    lesson_name?: string;
    lon?: number;
    subject?: string;
    subject_id?: number;
    teacher_id?: number;
  };
  "app.AttendanceConfirmData": {
    invite_token?: string;
  };
  "app.AttendanceGroupStatsData": {
    group_id?: number;
    subject_id?: number;
  };
  "app.ForgotPasswordData": {
    identity?: string;
  };
  "app.GradeItemCreateData": {
    deadline?: string;
    item_type?: string;
    max_score?: number;
    subject_id?: number;
    title?: string;
  };
  "app.GradeSubjectData": {
    subject_id?: number;
  };
  "app.GradeUpsertData": {
    comment?: string;
    item_id?: number;
    score?: number;
    session_id?: number;
    student_id?: number;
  };
  "app.GroupPerformanceData": {
    group_id?: number;
    subject_id?: number;
  };
  "app.LoginData": {
    login?: string;
    password?: string;
  };
  "app.RegisterByInviteData": {
    invite_code?: string;
    login?: string;
    password?: string;
  };
  "app.RegisterData": {
    invite_code?: string;
    login?: string;
    password?: string;
    role?: string;
    role_hash?: string;
  };
  "app.ResetPasswordData": {
    new_password?: string;
    token?: string;
  };
  "app.Response": {
    error?: string;
    id?: string;
    ok?: boolean;
    result?: unknown;
  };
  "app.TeacherAttendanceMarkData": {
    lesson_id?: number;
    status?: string;
    student_id?: number;
  };
  "app.TeacherAttendanceStudentHistoryData": {
    student_id?: number;
    subject_id?: number;
  };
  "app.TeacherStudentGradesData": {
    student_id?: number;
    subject_id?: number;
  };
  "app.TeacherStudentRadarData": {
    student_id?: number;
  };
  "app.UpdateEmailData": {
    email?: string;
  };
  "httpserver.loginResponse": {
    /** @example */
    error?: string;
    /** @example http-login */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.loginResult"];
  };
  "httpserver.loginResult": {
    /** @example teacher_test */
    login?: string;
    /** @example teacher */
    role?: string;
    /** @example <jwt_token> */
    token?: string;
    /** @example 3 */
    user_ID?: string;
  };
  "httpserver.profileResponse": {
    /** @example */
    error?: string;
    /** @example http-profile */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.profileResult"];
  };
  "httpserver.profileResult": {
    /** @example https://server.com/uploads/avatars/avatar.png */
    avatar?: string;
    /** @example ИКС-433 */
    group?: string;
    /** @example 237 */
    group_id?: number;
    /** @example ИКС-433 */
    group_name?: string;
    /** @example Преподаватель */
    job_title?: string;
    /** @example 1 */
    lectern_id?: number;
    /** @example student_iks_21 */
    login?: string;
    /** @example Демин Сергей А. */
    name?: string;
    /** @example 04:XX:YY:ZZ */
    nfc_tag?: string;
    /** @example student */
    role?: string;
    /** @example 56 */
    student_id?: number;
    /** @example Демин Сергей А. */
    student_name?: string;
    /** @example 3 */
    teacher_id?: number;
    /** @example Солодов Павел Сергеевич */
    teacher_name?: string;
    /** @example 0 */
    total_cheat_attempts?: number;
    /** @example 3 */
    user_id?: string;
  };
  "httpserver.registerByInviteResponse": {
    /** @example */
    error?: string;
    /** @example http-register-by-invite */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.registerByInviteResult"];
  };
  "httpserver.registerByInviteResult": {
    /** @example 237 */
    group_id?: number;
    /** @example ИКС-433 */
    group_name?: string;
    /** @example Преподаватель */
    job_title?: string;
    /** @example student_iks_21 */
    login?: string;
    /** @example student */
    role?: string;
    /** @example 56 */
    student_id?: number;
    /** @example Демин Сергей А. */
    student_name?: string;
    /** @example 3 */
    teacher_id?: number;
    /** @example Солодов Павел Сергеевич */
    teacher_name?: string;
    /** @example 12 */
    user_id?: string;
  };
  "httpserver.registerResponse": {
    /** @example */
    error?: string;
    /** @example http-register */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.registerResult"];
  };
  "httpserver.registerResult": {
    /** @example teacher1 */
    login?: string;
    /** @example teacher */
    role?: string;
    /** @example <jwt_token> */
    token?: string;
    /** @example 5 */
    user_id?: string;
  };
  "httpserver.studentAttendanceConfirmResponse": {
    /** @example */
    error?: string;
    /** @example http-attendance-confirm */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.studentAttendanceConfirmResult"];
  };
  "httpserver.studentAttendanceConfirmResult": {
    /** @example confirmed */
    attendance?: string;
    /** @example 5 */
    lesson_id?: string;
    /** @example 2026-04-20T20:13:07+07:00 */
    marked_at?: string;
    /** @example 4 */
    student_id?: string;
    /** @example 2 */
    subject_id?: number;
    /** @example 3 */
    teacher_id?: string;
  };
  "httpserver.studentAttendanceHistoryItem": {
    /** @example 1 */
    count?: number;
    /** @example 2026-04-20 */
    date?: string;
  };
  "httpserver.studentAttendanceHistoryResponse": {
    /** @example */
    error?: string;
    /** @example http-student-attendance-history */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.studentAttendanceHistoryResult"];
  };
  "httpserver.studentAttendanceHistoryResult": {
    items?: definitions["httpserver.studentAttendanceHistoryItem"][];
    /** @example 2026 */
    year?: number;
  };
  "httpserver.teacherActiveAttendanceSessionItem": {
    /** @example 72 */
    attendance_percent?: number;
    /** @example 2026-04-21T21:05:37+07:00 */
    created_at?: string;
    /** @example 2026-04-21T21:25:37+07:00 */
    expires_at?: string;
    /** @example 5 */
    id?: number;
    /** @example true */
    is_active?: boolean;
    /** @example 5 */
    lesson_id?: number;
    /** @example Networks */
    lesson_name?: string;
    /** @example 18 */
    marked_count?: number;
    /** @example 900 */
    remaining_seconds?: number;
    /** @example 25 */
    roster_size?: number;
    /** @example 900 */
    seconds_remaining?: number;
    /** @example 2026-04-21T21:10:37+07:00 */
    server_time?: string;
    /** @example 2 */
    subject_id?: number;
    /** @example 3 */
    teacher_id?: number;
    /** @example Asia/Novosibirsk */
    timezone?: string;
  };
  "httpserver.teacherActiveAttendanceSessionResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-active-attendance-session */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherActiveAttendanceSessionResult"];
  };
  "httpserver.teacherActiveAttendanceSessionResult": {
    /** @example true */
    active?: boolean;
    /** @example 900 */
    remaining_seconds?: number;
    /** @example 900 */
    seconds_remaining?: number;
    /** @example 2026-04-21T21:10:37+07:00 */
    server_time?: string;
    session?: definitions["httpserver.teacherActiveAttendanceSessionItem"];
    /** @example Asia/Novosibirsk */
    timezone?: string;
  };
  "httpserver.teacherAttendanceGroupResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-attendance-group */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherAttendanceGroupResult"];
  };
  "httpserver.teacherAttendanceGroupResult": {
    /** @example 1 */
    group_id?: number;
    students?: definitions["httpserver.teacherAttendanceGroupStudent"][];
    /** @example 2 */
    subject_id?: number;
    summary?: definitions["httpserver.teacherAttendanceGroupSummary"];
    /** @example Asia/Novosibirsk */
    timezone?: string;
  };
  "httpserver.teacherAttendanceGroupStudent": {
    /** @example 66.67 */
    attendance_percent?: number;
    /** @example 2 */
    attended_sessions?: number;
    /** @example 0 */
    excused_sessions?: number;
    /** @example 2026-04-20T20:13:07+07:00 */
    last_marked_at?: string;
    /** @example 4 */
    student_id?: number;
    /** @example Test Student */
    student_name?: string;
    /** @example 3 */
    total_sessions?: number;
  };
  "httpserver.teacherAttendanceGroupSummary": {
    /** @example 3 */
    sessions_count?: number;
    /** @example 1 */
    students_count?: number;
  };
  "httpserver.teacherAttendanceLinkRequest": {
    /** @example 20 */
    expires_minutes?: number;
    /**
     * @example [
     *   1
     * ]
     */
    group_ids?: number[];
    /** @example 5 */
    lesson_id?: number;
    /** @example Networks */
    lesson_name?: string;
    /** @example 2 */
    subject_id?: number;
  };
  "httpserver.teacherAttendanceLinkResponse": {
    /** @example */
    error?: string;
    /** @example http-attendance-link */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherAttendanceLinkResult"];
  };
  "httpserver.teacherAttendanceLinkResult": {
    /** @example 2026-04-21T21:25:37+07:00 */
    expires_at?: string;
    /** @example 20 */
    expires_minutes?: number;
    group_ids?: number[];
    /** @example <attendance_invite_jwt> */
    invite_token?: string;
    /** @example http://localhost:3000/attendance/join?token=<attendance_invite_jwt> */
    join_url?: string;
    /** @example 5 */
    lesson_id?: string;
    /** @example Networks */
    lesson_name?: string;
    /** @example http://localhost:3000/attendance/join?token=<attendance_invite_jwt> */
    qr_payload?: string;
    /** @example 25 */
    roster_size?: number;
    /** @example 2026-04-21T22:25:24+07:00 */
    schedule_end?: string;
    /** @example 2026-04-21T21:15:24+07:00 */
    schedule_start?: string;
    /** @example 2 */
    subject_id?: number;
    /** @example 3 */
    teacher_id?: string;
    /** @example Asia/Novosibirsk */
    timezone?: string;
    /** @example http://localhost:3000/attendance/join?token=<attendance_invite_jwt> */
    url?: string;
  };
  "httpserver.teacherAttendanceMarkedCountResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-attendance-marked-count */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherAttendanceMarkedCountResult"];
  };
  "httpserver.teacherAttendanceMarkedCountResult": {
    /** @example 72 */
    attendance_percent?: number;
    /** @example 5 */
    lesson_id?: number;
    /** @example 18 */
    marked_count?: number;
    /** @example 25 */
    roster_size?: number;
  };
  "httpserver.teacherAttendanceSessionTimerResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-attendance-session-timer */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherAttendanceSessionTimerResult"];
  };
  "httpserver.teacherAttendanceSessionTimerResult": {
    /** @example 2026-04-21T21:25:37+07:00 */
    expires_at?: string;
    /** @example true */
    is_active?: boolean;
    /** @example 5 */
    lesson_id?: number;
    /** @example 900 */
    remaining_seconds?: number;
    /** @example 900 */
    seconds_remaining?: number;
    /** @example 2026-04-21T21:10:37+07:00 */
    server_time?: string;
    /** @example Asia/Novosibirsk */
    timezone?: string;
  };
  "httpserver.teacherAttendanceStudentHistoryItem": {
    /** @example 2026-04-20 */
    date?: string;
    /** @example Math */
    lesson_name?: string;
    /** @example attended */
    status?: string;
  };
  "httpserver.teacherAttendanceStudentHistoryResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-attendance-student-history */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherAttendanceStudentHistoryResult"];
  };
  "httpserver.teacherAttendanceStudentHistoryResult": {
    items?: definitions["httpserver.teacherAttendanceStudentHistoryItem"][];
  };
  "httpserver.teacherGroupPerformanceResponse": {
    /** @example */
    error?: string;
    /** @example http-teacher-group-performance */
    id?: string;
    /** @example true */
    ok?: boolean;
    result?: definitions["httpserver.teacherGroupPerformanceResult"];
  };
  "httpserver.teacherGroupPerformanceResult": {
    /** @example 2 */
    group_id?: number;
    /** @example ИКС-433 */
    group_name?: string;
    students?: definitions["httpserver.teacherGroupPerformanceStudent"][];
    /** @example 1 */
    subject_id?: number;
    /** @example Networks */
    subject_name?: string;
    summary?: definitions["httpserver.teacherGroupPerformanceSummary"];
    /** @example Asia/Novosibirsk */
    timezone?: string;
  };
  "httpserver.teacherGroupPerformanceStudent": {
    /** @example 75 */
    attendance_percent?: number;
    /** @example 3 */
    attended_sessions?: number;
    /** @example 13 */
    current_score?: number;
    /** @example 0 */
    excused_sessions?: number;
    /** @example 65 */
    grade_percent?: number;
    /** @example 10 */
    passed_max?: number;
    /** @example 4 */
    student_id?: number;
    /** @example Test Student */
    student_name?: string;
    /** @example 20 */
    total_max?: number;
    /** @example 4 */
    total_sessions?: number;
  };
  "httpserver.teacherGroupPerformanceSummary": {
    /** @example 75 */
    avg_attendance_percent?: number;
    /** @example 65 */
    avg_grade_percent?: number;
    /** @example 4 */
    sessions_count?: number;
    /** @example 1 */
    students_count?: number;
  };
}

export interface operations {}

export interface external {}
