import { describe, expect, test } from '@jest/globals';
import { getJoinInviteToken } from './attendanceJoin';

describe('getJoinInviteToken', () => {
  test('reads a token from the hash route generated by the backend', () => {
    expect(getJoinInviteToken({
      hash: '#/attendance/join?token=new-token',
      pathname: '/',
      search: ''
    })).toBe('new-token');
  });

  test('keeps old non-hash attendance links working', () => {
    expect(getJoinInviteToken({
      hash: '',
      pathname: '/attendance/join',
      search: '?token=legacy-token'
    })).toBe('legacy-token');
  });

  test('ignores unrelated application routes', () => {
    expect(getJoinInviteToken({
      hash: '#/schedule',
      pathname: '/',
      search: '?token=unrelated-token'
    })).toBe('');
  });
});
