// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/student/attendance/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Student confirms attendance for active session.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendance"
                ],
                "summary": "Confirm attendance by invite token",
                "parameters": [
                    {
                        "description": "Attendance confirm payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.AttendanceConfirmData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.studentAttendanceConfirmResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/student/attendance/history": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns attendance marks grouped by date for current student and selected year.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendance"
                ],
                "summary": "Get current student attendance history",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 2026,
                        "description": "History year",
                        "name": "year",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.studentAttendanceHistoryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/student/grades": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Student gets own grade sheet for a subject.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Get current student grades by subject",
                "parameters": [
                    {
                        "description": "Subject payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.GradeSubjectData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/attendance-link": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher creates attendance session and gets invite/join URL. If subject_id/group_ids are omitted, they are taken from nearest scheduled lesson.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendance"
                ],
                "summary": "Create attendance session link",
                "parameters": [
                    {
                        "description": "Attendance session payload (subject_id/group_ids are optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.teacherAttendanceLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.teacherAttendanceLinkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/attendance/group": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns per-student attendance stats for selected group and optional subject.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendance"
                ],
                "summary": "Get attendance stats by group",
                "parameters": [
                    {
                        "description": "Group stats payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.AttendanceGroupStatsData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.teacherAttendanceGroupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/attendance/session": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher creates attendance session and gets invite/join URL. If subject_id/group_ids are omitted, they are taken from nearest scheduled lesson.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "attendance"
                ],
                "summary": "Create attendance session link",
                "parameters": [
                    {
                        "description": "Attendance session payload (subject_id/group_ids are optional)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.teacherAttendanceLinkRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.teacherAttendanceLinkResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/grades": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher creates or updates a student's score for a grade item.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Create or update student grade",
                "parameters": [
                    {
                        "description": "Grade payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.GradeUpsertData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/grades/items": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher creates a subject grade item/control point.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Create grade item",
                "parameters": [
                    {
                        "description": "Grade item payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.GradeItemCreateData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/grades/items/list": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher lists grade items/control points for assigned subject.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "List grade items by subject",
                "parameters": [
                    {
                        "description": "Subject payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.GradeSubjectData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/api/teacher/grades/student": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Teacher gets a student's grade sheet for an assigned subject.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grades"
                ],
                "summary": "Get student grades by subject",
                "parameters": [
                    {
                        "description": "Student subject payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.TeacherStudentGradesData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates a user and returns JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.LoginData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.loginResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns current user profile from Authorization token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get user profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.profileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Registers a user by login/password and role hash.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register user",
                "parameters": [
                    {
                        "description": "Register payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.RegisterData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.registerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        },
        "/register/by-invite": {
            "post": {
                "description": "Creates student account by one-time invite code from database.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Register student by invite code",
                "parameters": [
                    {
                        "description": "Register by invite payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.RegisterByInviteData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpserver.registerByInviteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_TelecomDep_ejournal_backend_internal_app.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_TelecomDep_ejournal_backend_internal_app.AttendanceConfirmData": {
            "type": "object",
            "properties": {
                "invite_token": {
                    "type": "string"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.AttendanceGroupStatsData": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer"
                },
                "subject_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.GradeItemCreateData": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "item_type": {
                    "type": "string"
                },
                "max_score": {
                    "type": "integer"
                },
                "subject_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.GradeSubjectData": {
            "type": "object",
            "properties": {
                "subject_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.GradeUpsertData": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "item_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "integer"
                },
                "student_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.LoginData": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.RegisterByInviteData": {
            "type": "object",
            "properties": {
                "invite_code": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.RegisterData": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role_hash": {
                    "type": "string"
                }
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.Response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "result": {}
            }
        },
        "github_com_TelecomDep_ejournal_backend_internal_app.TeacherStudentGradesData": {
            "type": "object",
            "properties": {
                "student_id": {
                    "type": "integer"
                },
                "subject_id": {
                    "type": "integer"
                }
            }
        },
        "internal_httpserver.loginResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-login"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.loginResult"
                }
            }
        },
        "internal_httpserver.loginResult": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "teacher_test"
                },
                "role": {
                    "type": "string",
                    "example": "teacher"
                },
                "token": {
                    "type": "string",
                    "example": "\u003cjwt_token\u003e"
                },
                "user_ID": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "internal_httpserver.profileResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-profile"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.profileResult"
                }
            }
        },
        "internal_httpserver.profileResult": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer",
                    "example": 237
                },
                "group_name": {
                    "type": "string",
                    "example": "ИКС-433"
                },
                "job_title": {
                    "type": "string",
                    "example": "Преподаватель"
                },
                "lectern_id": {
                    "type": "integer",
                    "example": 1
                },
                "login": {
                    "type": "string",
                    "example": "student_iks_21"
                },
                "name": {
                    "type": "string",
                    "example": "Демин Сергей А."
                },
                "role": {
                    "type": "string",
                    "example": "student"
                },
                "student_id": {
                    "type": "integer",
                    "example": 56
                },
                "student_name": {
                    "type": "string",
                    "example": "Демин Сергей А."
                },
                "teacher_id": {
                    "type": "integer",
                    "example": 3
                },
                "teacher_name": {
                    "type": "string",
                    "example": "Солодов Павел Сергеевич"
                },
                "user_id": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "internal_httpserver.registerByInviteResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-register-by-invite"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.registerByInviteResult"
                }
            }
        },
        "internal_httpserver.registerByInviteResult": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer",
                    "example": 237
                },
                "group_name": {
                    "type": "string",
                    "example": "ИКС-433"
                },
                "login": {
                    "type": "string",
                    "example": "student_iks_21"
                },
                "role": {
                    "type": "string",
                    "example": "student"
                },
                "student_id": {
                    "type": "integer",
                    "example": 56
                },
                "student_name": {
                    "type": "string",
                    "example": "Демин Сергей А."
                },
                "user_id": {
                    "type": "string",
                    "example": "12"
                }
            }
        },
        "internal_httpserver.registerResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-register"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.registerResult"
                }
            }
        },
        "internal_httpserver.registerResult": {
            "type": "object",
            "properties": {
                "login": {
                    "type": "string",
                    "example": "teacher1"
                },
                "role": {
                    "type": "string",
                    "example": "teacher"
                },
                "user_id": {
                    "type": "string",
                    "example": "5"
                }
            }
        },
        "internal_httpserver.studentAttendanceConfirmResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-attendance-confirm"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.studentAttendanceConfirmResult"
                }
            }
        },
        "internal_httpserver.studentAttendanceConfirmResult": {
            "type": "object",
            "properties": {
                "attendance": {
                    "type": "string",
                    "example": "confirmed"
                },
                "lesson_id": {
                    "type": "string",
                    "example": "5"
                },
                "marked_at": {
                    "type": "string",
                    "example": "2026-04-20T20:13:07+07:00"
                },
                "student_id": {
                    "type": "string",
                    "example": "4"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 2
                },
                "teacher_id": {
                    "type": "string",
                    "example": "3"
                }
            }
        },
        "internal_httpserver.studentAttendanceHistoryItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 1
                },
                "date": {
                    "type": "string",
                    "example": "2026-04-20"
                }
            }
        },
        "internal_httpserver.studentAttendanceHistoryResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-student-attendance-history"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.studentAttendanceHistoryResult"
                }
            }
        },
        "internal_httpserver.studentAttendanceHistoryResult": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_httpserver.studentAttendanceHistoryItem"
                    }
                },
                "year": {
                    "type": "integer",
                    "example": 2026
                }
            }
        },
        "internal_httpserver.teacherAttendanceGroupResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-teacher-attendance-group"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.teacherAttendanceGroupResult"
                }
            }
        },
        "internal_httpserver.teacherAttendanceGroupResult": {
            "type": "object",
            "properties": {
                "group_id": {
                    "type": "integer",
                    "example": 1
                },
                "students": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal_httpserver.teacherAttendanceGroupStudent"
                    }
                },
                "subject_id": {
                    "type": "integer",
                    "example": 2
                },
                "summary": {
                    "$ref": "#/definitions/internal_httpserver.teacherAttendanceGroupSummary"
                },
                "timezone": {
                    "type": "string",
                    "example": "Asia/Novosibirsk"
                }
            }
        },
        "internal_httpserver.teacherAttendanceGroupStudent": {
            "type": "object",
            "properties": {
                "attendance_percent": {
                    "type": "number",
                    "example": 66.67
                },
                "attended_sessions": {
                    "type": "integer",
                    "example": 2
                },
                "last_marked_at": {
                    "type": "string",
                    "example": "2026-04-20T20:13:07+07:00"
                },
                "student_id": {
                    "type": "integer",
                    "example": 4
                },
                "student_name": {
                    "type": "string",
                    "example": "Test Student"
                },
                "total_sessions": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "internal_httpserver.teacherAttendanceGroupSummary": {
            "type": "object",
            "properties": {
                "sessions_count": {
                    "type": "integer",
                    "example": 3
                },
                "students_count": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "internal_httpserver.teacherAttendanceLinkRequest": {
            "type": "object",
            "properties": {
                "expires_minutes": {
                    "type": "integer",
                    "example": 20
                },
                "group_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1
                    ]
                },
                "lesson_name": {
                    "type": "string",
                    "example": "Networks"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "internal_httpserver.teacherAttendanceLinkResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": ""
                },
                "id": {
                    "type": "string",
                    "example": "http-attendance-link"
                },
                "ok": {
                    "type": "boolean",
                    "example": true
                },
                "result": {
                    "$ref": "#/definitions/internal_httpserver.teacherAttendanceLinkResult"
                }
            }
        },
        "internal_httpserver.teacherAttendanceLinkResult": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string",
                    "example": "2026-04-21T21:25:37+07:00"
                },
                "expires_minutes": {
                    "type": "integer",
                    "example": 20
                },
                "group_ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "invite_token": {
                    "type": "string",
                    "example": "\u003cattendance_invite_jwt\u003e"
                },
                "join_url": {
                    "type": "string",
                    "example": "http://localhost:3000/attendance/join?token=\u003cattendance_invite_jwt\u003e"
                },
                "lesson_id": {
                    "type": "string",
                    "example": "5"
                },
                "lesson_name": {
                    "type": "string",
                    "example": "Networks"
                },
                "qr_payload": {
                    "type": "string",
                    "example": "http://localhost:3000/attendance/join?token=\u003cattendance_invite_jwt\u003e"
                },
                "roster_size": {
                    "type": "integer",
                    "example": 25
                },
                "schedule_end": {
                    "type": "string",
                    "example": "2026-04-21T22:25:24+07:00"
                },
                "schedule_start": {
                    "type": "string",
                    "example": "2026-04-21T21:15:24+07:00"
                },
                "subject_id": {
                    "type": "integer",
                    "example": 2
                },
                "teacher_id": {
                    "type": "string",
                    "example": "3"
                },
                "timezone": {
                    "type": "string",
                    "example": "Asia/Novosibirsk"
                },
                "url": {
                    "type": "string",
                    "example": "http://localhost:3000/attendance/join?token=\u003cattendance_invite_jwt\u003e"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "EJournal Backend API",
	Description:      "Backend API for e-journal, attendance links and invite registration.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
